function [svdX] = func_svdByRank(X)
[U, S, V] = svd(X, 'econ');
Nk = rank(X);
U = U(:, 1:Nk);
V = V(:, 1:Nk);
s = diag(S(1:Nk, 1:Nk));

svdX = struct(...
    'matrix', X, ...
    'U', U, ...
    'V', V, ...
    's', s...
    );
end